# Generated by Django 4.0 on 2022-01-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
