# Generated by Django 4.0 on 2022-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
